name: freecodecamp
version: master
summary: Learn to code and help nonprofits
description: |
  Free Code Camp is a friendly open source community where you learn to code and
  help nonprofits.
  We help our campers build job-worthy portfolios of real apps used by real
  people, while helping nonprofits.

  You start by working through our self-paced, browser-based full stack
  JavaScript curriculum.

grade: devel
confinement: strict

parts:
  freecodecamp:
    source: .
    plugin: nodejs
    after: [mongodb]
